name: update all submodules
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Submodule update
      run: |
        git submodule init
        git submodule update --remote --merge
        git config --local user.email "4097471+pythoninthegrass@users.noreply.github.com"
        git config --local user.name "pythoninthegrass"
        git commit -m "update submodule" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DEPLOY_KEY }}
        branch: ${{ github.ref }}
